### ISSUE TITLE
Bug: demo admin panel website login

### ISSUE THREAD

**Issue by vladimirbalin** [thecodeholic/laravel-vue-ecommerce#1]
When I try to login with an existing admin account on the demo admin panel with next login and password: 
```
Email: admin@example.com
Password: admin123
```
It says 'Email or password is incorrect', checked for spaces, still doesn't work

**Comment by thecodeholic** [comment]
@vladimirbalin Will check it and get back to you soon.

**Comment by thecodeholic** [comment]
Someone had changed the email of the admin user. I reset the data. 
Now login works. 
Maybe I need to restrict update and delete in Demo environment.
All products were deleted.

**Comment by AsrorbekDev** [comment]
> Someone had changed the email of the admin user. I reset the data. Now login works. Maybe I need to restrict update and delete in Demo environment. All products were deleted.

Good job!!
